# Generated by Django 2.2.9 on 2021-06-03 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='Sender Name')),
                ('from_email', models.EmailField(max_length=255, verbose_name='Sender E-mail')),
                ('phone', models.CharField(blank=True, max_length=15, null=True, verbose_name='Sender Phone Number')),
                ('subject', models.CharField(blank=True, max_length=255, null=True, verbose_name='Message Subject')),
                ('message', models.TextField(verbose_name='Message Text')),
                ('sent', models.DateTimeField(auto_now_add=True, verbose_name='Sent')),
            ],
            options={
                'verbose_name': 'E-mail Message',
                'verbose_name_plural': 'E-mail Messages',
            },
        ),
    ]
